plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.googlepay'
version = '0.1.1'

android {
  namespace "expo.modules.googlepay"
  defaultConfig {
    versionCode 1
    versionName "0.1.1"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "com.google.android.gms:play-services-wallet:20.0.0"
}
